// Code generated by cmd/sdkgen; DO NOT EDIT.
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

type Endpoint struct {
	Method string
	Path   string
}

var Endpoints = map[string]Endpoint{
	"GetApiV1AuditEvents":                                 {Method: "GET", Path: "/api/v1/audit/events"},
	"GetApiV1AuditEventsExport":                           {Method: "GET", Path: "/api/v1/audit/events/export"},
	"GetApiV1AuthMe":                                      {Method: "GET", Path: "/api/v1/auth/me"},
	"GetApiV1BuildRuns":                                   {Method: "GET", Path: "/api/v1/build-runs"},
	"GetApiV1BuildRunsNamespaceName":                      {Method: "GET", Path: "/api/v1/build-runs/{namespace}/{name}"},
	"GetApiV1BuildRunsNamespaceNameArtifacts":             {Method: "GET", Path: "/api/v1/build-runs/{namespace}/{name}/artifacts"},
	"GetApiV1BuildRunsNamespaceNameArtifactsArtifactName": {Method: "GET", Path: "/api/v1/build-runs/{namespace}/{name}/artifacts/{artifactName}"},
	"GetApiV1BuildRunsNamespaceNameLogs":                  {Method: "GET", Path: "/api/v1/build-runs/{namespace}/{name}/logs"},
	"GetApiV1CatalogPipelineTemplates":                    {Method: "GET", Path: "/api/v1/catalog/pipeline-templates"},
	"GetApiV1ClusterTargets":                              {Method: "GET", Path: "/api/v1/cluster-targets"},
	"GetApiV1Environments":                                {Method: "GET", Path: "/api/v1/environments"},
	"GetApiV1Organizations":                               {Method: "GET", Path: "/api/v1/organizations"},
	"GetApiV1OrganizationsOrganizationMembers":            {Method: "GET", Path: "/api/v1/organizations/{organization}/members"},
	"GetApiV1OrganizationsOrganizationProjectAccess":      {Method: "GET", Path: "/api/v1/organizations/{organization}/project-access"},
	"GetApiV1OrganizationsOrganizationTeams":              {Method: "GET", Path: "/api/v1/organizations/{organization}/teams"},
	"GetApiV1PipelineTemplates":                           {Method: "GET", Path: "/api/v1/pipeline-templates"},
	"GetApiV1Plugins":                                     {Method: "GET", Path: "/api/v1/plugins"},
	"GetApiV1PluginsHealth":                               {Method: "GET", Path: "/api/v1/plugins/health"},
	"GetApiV1PluginsTypeName":                             {Method: "GET", Path: "/api/v1/plugins/{type}/{name}"},
	"GetApiV1Projects":                                    {Method: "GET", Path: "/api/v1/projects"},
	"GetApiV1ProjectsName":                                {Method: "GET", Path: "/api/v1/projects/{name}"},
	"GetApiV1Providers":                                   {Method: "GET", Path: "/api/v1/providers"},
	"GetApiV1ProvidersHealth":                             {Method: "GET", Path: "/api/v1/providers/health"},
	"GetApiV1Releases":                                    {Method: "GET", Path: "/api/v1/releases"},
	"GetApiV1ReportsBuilds":                               {Method: "GET", Path: "/api/v1/reports/builds"},
	"GetApiV1ReportsReleases":                             {Method: "GET", Path: "/api/v1/reports/releases"},
	"GetApiV1ReportsSecurity":                             {Method: "GET", Path: "/api/v1/reports/security"},
	"GetApiV1Repositories":                                {Method: "GET", Path: "/api/v1/repositories"},
	"GetHealthz":                                          {Method: "GET", Path: "/healthz"},
	"GetMetrics":                                          {Method: "GET", Path: "/metrics"},
	"GetReadyz":                                           {Method: "GET", Path: "/readyz"},
	"PostApiV1BuildRuns":                                  {Method: "POST", Path: "/api/v1/build-runs"},
	"PostApiV1BuildRunsNamespaceNameCancel":               {Method: "POST", Path: "/api/v1/build-runs/{namespace}/{name}/cancel"},
	"PostApiV1BuildRunsNamespaceNameRerun":                {Method: "POST", Path: "/api/v1/build-runs/{namespace}/{name}/rerun"},
	"PostApiV1BuildRunsNamespaceNameRetry":                {Method: "POST", Path: "/api/v1/build-runs/{namespace}/{name}/retry"},
	"PostApiV1CatalogPipelineTemplatesNameInstall":        {Method: "POST", Path: "/api/v1/catalog/pipeline-templates/{name}/install"},
	"PostApiV1PipelineTemplates":                          {Method: "POST", Path: "/api/v1/pipeline-templates"},
	"PostApiV1Projects":                                   {Method: "POST", Path: "/api/v1/projects"},
	"PostApiV1ProjectsNameCachePurge":                     {Method: "POST", Path: "/api/v1/projects/{name}/cache/purge"},
	"PostApiV1ReleasesNamespaceNameApprove":               {Method: "POST", Path: "/api/v1/releases/{namespace}/{name}/approve"},
	"PostApiV1ReleasesNamespaceNamePromote":               {Method: "POST", Path: "/api/v1/releases/{namespace}/{name}/promote"},
	"PostApiV1ReleasesNamespaceNameReject":                {Method: "POST", Path: "/api/v1/releases/{namespace}/{name}/reject"},
	"PostApiV1ReleasesNamespaceNameRollback":              {Method: "POST", Path: "/api/v1/releases/{namespace}/{name}/rollback"},
	"PostApiV1Repositories":                               {Method: "POST", Path: "/api/v1/repositories"},
	"PostApiV1WebhooksGenericRepositoryName":              {Method: "POST", Path: "/api/v1/webhooks/generic/{repositoryName}"},
	"PostApiV1WebhooksGiteaRepositoryName":                {Method: "POST", Path: "/api/v1/webhooks/gitea/{repositoryName}"},
	"PostApiV1WebhooksGithubRepositoryName":               {Method: "POST", Path: "/api/v1/webhooks/github/{repositoryName}"},
	"PostApiV1WebhooksGitlabRepositoryName":               {Method: "POST", Path: "/api/v1/webhooks/gitlab/{repositoryName}"},
	"PutApiV1PipelineTemplatesNamespaceName":              {Method: "PUT", Path: "/api/v1/pipeline-templates/{namespace}/{name}"},
}

type APIError struct {
	Code      string `json:"code"`
	Message   string `json:"message"`
	RequestID string `json:"requestId,omitempty"`
}

func (e APIError) Error() string { return e.Code + ": " + e.Message }

type Client struct {
	BaseURL      string
	HTTPClient   *http.Client
	Token        string
	Organization string
}

func (c Client) Do(ctx context.Context, operation string, pathValues, query map[string]string, body, out any) error {
	endpoint, ok := Endpoints[operation]
	if !ok {
		return fmt.Errorf("unsupported operation %q", operation)
	}
	path := endpoint.Path
	for key, value := range pathValues {
		path = strings.ReplaceAll(path, "{"+key+"}", url.PathEscape(value))
	}
	parsed, err := url.Parse(strings.TrimSuffix(c.BaseURL, "/") + path)
	if err != nil {
		return fmt.Errorf("build URL: %w", err)
	}
	values := parsed.Query()
	for key, value := range query {
		values.Set(key, value)
	}
	parsed.RawQuery = values.Encode()
	var reader io.Reader
	if body != nil {
		data, err := json.Marshal(body)
		if err != nil {
			return fmt.Errorf("encode request: %w", err)
		}
		reader = bytes.NewReader(data)
	}
	request, err := http.NewRequestWithContext(ctx, endpoint.Method, parsed.String(), reader)
	if err != nil {
		return err
	}
	if body != nil {
		request.Header.Set("Content-Type", "application/json")
	}
	if c.Token != "" {
		request.Header.Set("Authorization", "Bearer "+c.Token)
	}
	if c.Organization != "" {
		request.Header.Set("X-Cloudivision-Organization", c.Organization)
	}
	httpClient := c.HTTPClient
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	response, err := httpClient.Do(request)
	if err != nil {
		return err
	}
	defer response.Body.Close()
	if response.StatusCode >= 400 {
		var apiErr APIError
		if json.NewDecoder(response.Body).Decode(&apiErr) != nil {
			apiErr = APIError{Code: response.Status, Message: response.Status}
		}
		return apiErr
	}
	if out != nil && response.StatusCode != http.StatusNoContent {
		if err := json.NewDecoder(response.Body).Decode(out); err != nil {
			return fmt.Errorf("decode response: %w", err)
		}
	}
	return nil
}
