{{- range $component := list "controller" "api" "web" }}
{{- $values := index $.Values $component }}
{{- if $values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "cloudivision.fullname" $ }}-{{ $component }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "cloudivision.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
spec:
  maxUnavailable: {{ $values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "cloudivision.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $component }}
---
{{- end }}
{{- end }}
