{{- if and (or .Values.database.enabled (eq .Values.audit.backend "postgres")) (not .Values.database.externalUrlSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudivision.fullname" . }}-database
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudivision.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: "postgres://user:password@postgres:5432/cloudivision?sslmode=require"
{{- end }}
