apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cloudivision.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudivision.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cloudivision.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudivision.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cloudivision.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudivision.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
