apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudivision.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudivision.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  selector:
    {{- include "cloudivision.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudivision.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudivision.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.web.service.type }}
  selector:
    {{- include "cloudivision.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: http
