apiVersion: cicd.cloudivision.io/v1alpha1
kind: Release
metadata:
  name: sample-release
spec:
  projectRef: sample-project
  environmentRef: sample-environment
  buildRunRef: sample-buildrun
  image:
    repository: ghcr.io/cloudivision/example
    tag: main
    digest: sha256:example
  approval:
    required: false
  strategy: gitops
