apiVersion: cicd.cloudivision.io/v1alpha1
kind: Repository
metadata:
  name: demo-repository
  namespace: cloudivision
spec:
  projectRef: demo-project
  provider: generic
  url: https://github.com/cloudivision/cloudivision.git
  defaultBranch: main
  webhook:
    enabled: false
    events:
      - push
  pipelineTemplateRef: nodejs-demo
