apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  - apiGroups:
      - cicd.cloudivision.io
    resources:
      - buildruns
      - projects
      - releases
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cicd.cloudivision.io
    resources:
      - buildruns/status
      - projects/status
      - releases/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - cicd.cloudivision.io
    resources:
      - buildruns/finalizers
      - projects/finalizers
      - releases/finalizers
    verbs:
      - update
  - apiGroups:
      - cicd.cloudivision.io
    resources:
      - buildruns
      - environments
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
