apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  - apiGroups:
      - cicd.cloudivision.io
    resources:
      - buildruns
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cicd.cloudivision.io
    resources:
      - projects
      - repositories
      - pipelinetemplates
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - cicd.cloudivision.io
    resources:
      - buildruns/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - cicd.cloudivision.io
    resources:
      - buildruns/finalizers
    verbs:
      - update
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
