// Code generated by cmd/sdkgen; DO NOT EDIT.
export interface Endpoint { method: string; path: string; }
export const endpoints = { 
  GetApiV1AuditEvents: { method: 'GET', path: '/api/v1/audit/events' },
  GetApiV1AuditEventsExport: { method: 'GET', path: '/api/v1/audit/events/export' },
  GetApiV1AuthMe: { method: 'GET', path: '/api/v1/auth/me' },
  GetApiV1BuildRuns: { method: 'GET', path: '/api/v1/build-runs' },
  GetApiV1BuildRunsNamespaceName: { method: 'GET', path: '/api/v1/build-runs/{namespace}/{name}' },
  GetApiV1BuildRunsNamespaceNameArtifacts: { method: 'GET', path: '/api/v1/build-runs/{namespace}/{name}/artifacts' },
  GetApiV1BuildRunsNamespaceNameArtifactsArtifactName: { method: 'GET', path: '/api/v1/build-runs/{namespace}/{name}/artifacts/{artifactName}' },
  GetApiV1BuildRunsNamespaceNameLogs: { method: 'GET', path: '/api/v1/build-runs/{namespace}/{name}/logs' },
  GetApiV1CatalogPipelineTemplates: { method: 'GET', path: '/api/v1/catalog/pipeline-templates' },
  GetApiV1ClusterTargets: { method: 'GET', path: '/api/v1/cluster-targets' },
  GetApiV1Environments: { method: 'GET', path: '/api/v1/environments' },
  GetApiV1Organizations: { method: 'GET', path: '/api/v1/organizations' },
  GetApiV1OrganizationsOrganizationMembers: { method: 'GET', path: '/api/v1/organizations/{organization}/members' },
  GetApiV1OrganizationsOrganizationProjectAccess: { method: 'GET', path: '/api/v1/organizations/{organization}/project-access' },
  GetApiV1OrganizationsOrganizationTeams: { method: 'GET', path: '/api/v1/organizations/{organization}/teams' },
  GetApiV1PipelineTemplates: { method: 'GET', path: '/api/v1/pipeline-templates' },
  GetApiV1Projects: { method: 'GET', path: '/api/v1/projects' },
  GetApiV1ProjectsName: { method: 'GET', path: '/api/v1/projects/{name}' },
  GetApiV1Providers: { method: 'GET', path: '/api/v1/providers' },
  GetApiV1ProvidersHealth: { method: 'GET', path: '/api/v1/providers/health' },
  GetApiV1Releases: { method: 'GET', path: '/api/v1/releases' },
  GetApiV1ReportsBuilds: { method: 'GET', path: '/api/v1/reports/builds' },
  GetApiV1ReportsReleases: { method: 'GET', path: '/api/v1/reports/releases' },
  GetApiV1ReportsSecurity: { method: 'GET', path: '/api/v1/reports/security' },
  GetApiV1Repositories: { method: 'GET', path: '/api/v1/repositories' },
  GetHealthz: { method: 'GET', path: '/healthz' },
  GetMetrics: { method: 'GET', path: '/metrics' },
  GetReadyz: { method: 'GET', path: '/readyz' },
  PostApiV1BuildRuns: { method: 'POST', path: '/api/v1/build-runs' },
  PostApiV1BuildRunsNamespaceNameCancel: { method: 'POST', path: '/api/v1/build-runs/{namespace}/{name}/cancel' },
  PostApiV1BuildRunsNamespaceNameRerun: { method: 'POST', path: '/api/v1/build-runs/{namespace}/{name}/rerun' },
  PostApiV1BuildRunsNamespaceNameRetry: { method: 'POST', path: '/api/v1/build-runs/{namespace}/{name}/retry' },
  PostApiV1CatalogPipelineTemplatesNameInstall: { method: 'POST', path: '/api/v1/catalog/pipeline-templates/{name}/install' },
  PostApiV1PipelineTemplates: { method: 'POST', path: '/api/v1/pipeline-templates' },
  PostApiV1Projects: { method: 'POST', path: '/api/v1/projects' },
  PostApiV1ProjectsNameCachePurge: { method: 'POST', path: '/api/v1/projects/{name}/cache/purge' },
  PostApiV1ReleasesNamespaceNameApprove: { method: 'POST', path: '/api/v1/releases/{namespace}/{name}/approve' },
  PostApiV1ReleasesNamespaceNamePromote: { method: 'POST', path: '/api/v1/releases/{namespace}/{name}/promote' },
  PostApiV1ReleasesNamespaceNameReject: { method: 'POST', path: '/api/v1/releases/{namespace}/{name}/reject' },
  PostApiV1ReleasesNamespaceNameRollback: { method: 'POST', path: '/api/v1/releases/{namespace}/{name}/rollback' },
  PostApiV1Repositories: { method: 'POST', path: '/api/v1/repositories' },
  PostApiV1WebhooksGenericRepositoryName: { method: 'POST', path: '/api/v1/webhooks/generic/{repositoryName}' },
  PostApiV1WebhooksGiteaRepositoryName: { method: 'POST', path: '/api/v1/webhooks/gitea/{repositoryName}' },
  PostApiV1WebhooksGithubRepositoryName: { method: 'POST', path: '/api/v1/webhooks/github/{repositoryName}' },
  PostApiV1WebhooksGitlabRepositoryName: { method: 'POST', path: '/api/v1/webhooks/gitlab/{repositoryName}' },
  PutApiV1PipelineTemplatesNamespaceName: { method: 'PUT', path: '/api/v1/pipeline-templates/{namespace}/{name}' },
} as const;
export type OperationName = keyof typeof endpoints;
export interface ApiError { code: string; message: string; requestId?: string; }
export interface ClientOptions { baseUrl?: string; token?: string; organization?: string; fetch?: typeof fetch; }
export class CloudivisionClient {
  constructor(private readonly options: ClientOptions = {}) {}
  async request<T>(operation: OperationName, values: Record<string,string> = {}, query: Record<string,string> = {}, body?: unknown): Promise<T> {
    const endpoint=endpoints[operation];let path:string=endpoint.path;for(const [key,value] of Object.entries(values)){path=path.replaceAll('{'+key+'}',encodeURIComponent(value));}const target=new URL((this.options.baseUrl??'')+path,globalThis.location?.origin??'http://localhost');for(const [key,value] of Object.entries(query)){target.searchParams.set(key,value);}const headers:Record<string,string>={};if(body!==undefined)headers['Content-Type']='application/json';if(this.options.token)headers.Authorization='Bearer '+this.options.token;if(this.options.organization)headers['X-Cloudivision-Organization']=this.options.organization;const response=await (this.options.fetch??fetch)(target,{method:endpoint.method,headers,body:body===undefined?undefined:JSON.stringify(body)});if(!response.ok){throw await response.json() as ApiError;}return response.status===204?undefined as T:await response.json() as T;
  }
}
