package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"text/template"

	"gopkg.in/yaml.v3"
)

type operation struct{ Name, Method, Path string }
type document struct {
	OpenAPI    string                    `yaml:"openapi"`
	Paths      map[string]map[string]any `yaml:"paths"`
	Components struct {
		Schemas map[string]any `yaml:"schemas"`
	} `yaml:"components"`
}

func main() {
	specPath := flag.String("spec", "docs/openapi.yaml", "OpenAPI input")
	goPath := flag.String("go-out", "sdk/go/client.gen.go", "Go output")
	tsPath := flag.String("ts-out", "sdk/typescript/client.gen.ts", "TypeScript output")
	check := flag.Bool("check", false, "verify generated files")
	serverPath := flag.String("server", "internal/api/server.go", "API route source")
	flag.Parse()
	data, err := os.ReadFile(*specPath)
	must(err)
	var spec document
	must(yaml.Unmarshal(data, &spec))
	must(validate(spec))
	must(validateRoutes(spec, *serverPath))
	operations := operations(spec)
	goData, err := format.Source(render(goTemplate, operations))
	must(err)
	tsData := render(tsTemplate, operations)
	if *check {
		must(compare(*goPath, goData))
		must(compare(*tsPath, tsData))
		return
	}
	must(write(*goPath, goData))
	must(write(*tsPath, tsData))
}

func validateRoutes(spec document, serverPath string) error {
	data, err := os.ReadFile(serverPath)
	if err != nil {
		return err
	}
	re := regexp.MustCompile(`HandleFunc\("[A-Z]+ ([^"]+)"`)
	missing := []string{}
	for _, match := range re.FindAllStringSubmatch(string(data), -1) {
		if _, ok := spec.Paths[match[1]]; !ok {
			missing = append(missing, match[1])
		}
	}
	if len(missing) > 0 {
		sort.Strings(missing)
		return fmt.Errorf("OpenAPI is missing server routes: %s", strings.Join(missing, ", "))
	}
	return nil
}
func must(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
func validate(spec document) error {
	if !strings.HasPrefix(spec.OpenAPI, "3.") {
		return fmt.Errorf("unsupported OpenAPI version %q", spec.OpenAPI)
	}
	for _, name := range []string{"ErrorResponse", "PaginatedResponse"} {
		if _, ok := spec.Components.Schemas[name]; !ok {
			return fmt.Errorf("missing schema %s", name)
		}
	}
	for _, path := range []string{"/api/v1/auth/me", "/api/v1/build-runs/{namespace}/{name}/retry", "/api/v1/releases/{namespace}/{name}/rollback", "/api/v1/providers/health", "/api/v1/audit/events/export", "/api/v1/reports/security"} {
		if _, ok := spec.Paths[path]; !ok {
			return fmt.Errorf("missing required path %s", path)
		}
	}
	return nil
}
func operations(spec document) []operation {
	methods := map[string]bool{"get": true, "post": true, "put": true, "patch": true, "delete": true}
	out := []operation{}
	for path, item := range spec.Paths {
		for method := range item {
			method = strings.ToLower(method)
			if methods[method] {
				out = append(out, operation{Name: operationName(method, path), Method: strings.ToUpper(method), Path: path})
			}
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

var words = regexp.MustCompile(`[A-Za-z0-9]+`)

func operationName(method, path string) string {
	parts := append([]string{method}, words.FindAllString(path, -1)...)
	for i, p := range parts {
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return strings.Join(parts, "")
}
func render(source string, value any) []byte {
	parsed := template.Must(template.New("generated").Parse(source))
	var out bytes.Buffer
	must(parsed.Execute(&out, value))
	return out.Bytes()
}
func write(path string, data []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, data, 0o644)
}
func compare(path string, want []byte) error {
	got, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	if !bytes.Equal(got, want) {
		return fmt.Errorf("%s is stale; run make sdk-generate", path)
	}
	return nil
}

const goTemplate = `// Code generated by cmd/sdkgen; DO NOT EDIT.
package client

import (
 "bytes"
 "context"
 "encoding/json"
 "fmt"
 "io"
 "net/http"
 "net/url"
 "strings"
)

type Endpoint struct { Method string; Path string }
var Endpoints = map[string]Endpoint{
{{- range .}}
 "{{.Name}}": {Method:"{{.Method}}", Path:"{{.Path}}"},{{end}}
}
type APIError struct { Code string ` + "`json:\"code\"`" + `; Message string ` + "`json:\"message\"`" + `; RequestID string ` + "`json:\"requestId,omitempty\"`" + ` }
func (e APIError) Error() string { return e.Code+": "+e.Message }
type Client struct { BaseURL string; HTTPClient *http.Client; Token string; Organization string }
func (c Client) Do(ctx context.Context, operation string, pathValues, query map[string]string, body, out any) error {
 endpoint,ok:=Endpoints[operation];if !ok{return fmt.Errorf("unsupported operation %q",operation)};path:=endpoint.Path;for key,value:=range pathValues{path=strings.ReplaceAll(path,"{"+key+"}",url.PathEscape(value))};parsed,err:=url.Parse(strings.TrimSuffix(c.BaseURL,"/")+path);if err!=nil{return fmt.Errorf("build URL: %w",err)};values:=parsed.Query();for key,value:=range query{values.Set(key,value)};parsed.RawQuery=values.Encode();var reader io.Reader;if body!=nil{data,err:=json.Marshal(body);if err!=nil{return fmt.Errorf("encode request: %w",err)};reader=bytes.NewReader(data)};request,err:=http.NewRequestWithContext(ctx,endpoint.Method,parsed.String(),reader);if err!=nil{return err};if body!=nil{request.Header.Set("Content-Type","application/json")};if c.Token!=""{request.Header.Set("Authorization","Bearer "+c.Token)};if c.Organization!=""{request.Header.Set("X-Cloudivision-Organization",c.Organization)};httpClient:=c.HTTPClient;if httpClient==nil{httpClient=http.DefaultClient};response,err:=httpClient.Do(request);if err!=nil{return err};defer response.Body.Close();if response.StatusCode>=400{var apiErr APIError;if json.NewDecoder(response.Body).Decode(&apiErr)!=nil{apiErr=APIError{Code:response.Status,Message:response.Status}};return apiErr};if out!=nil&&response.StatusCode!=http.StatusNoContent{if err:=json.NewDecoder(response.Body).Decode(out);err!=nil{return fmt.Errorf("decode response: %w",err)}};return nil
}
`

const tsTemplate = `// Code generated by cmd/sdkgen; DO NOT EDIT.
export interface Endpoint { method: string; path: string; }
export const endpoints = { {{range .}}
  {{.Name}}: { method: '{{.Method}}', path: '{{.Path}}' },{{end}}
} as const;
export type OperationName = keyof typeof endpoints;
export interface ApiError { code: string; message: string; requestId?: string; }
export interface ClientOptions { baseUrl?: string; token?: string; organization?: string; fetch?: typeof fetch; }
export class CloudivisionClient {
  constructor(private readonly options: ClientOptions = {}) {}
  async request<T>(operation: OperationName, values: Record<string,string> = {}, query: Record<string,string> = {}, body?: unknown): Promise<T> {
    const endpoint=endpoints[operation];let path:string=endpoint.path;for(const [key,value] of Object.entries(values)){path=path.replaceAll('{'+key+'}',encodeURIComponent(value));}const target=new URL((this.options.baseUrl??'')+path,globalThis.location?.origin??'http://localhost');for(const [key,value] of Object.entries(query)){target.searchParams.set(key,value);}const headers:Record<string,string>={};if(body!==undefined)headers['Content-Type']='application/json';if(this.options.token)headers.Authorization='Bearer '+this.options.token;if(this.options.organization)headers['X-Cloudivision-Organization']=this.options.organization;const response=await (this.options.fetch??fetch)(target,{method:endpoint.method,headers,body:body===undefined?undefined:JSON.stringify(body)});if(!response.ok){throw await response.json() as ApiError;}return response.status===204?undefined as T:await response.json() as T;
  }
}
`
