//go:build !ignore_autogenerated

package v1alpha1

import (
	"encoding/json"

	"k8s.io/apimachinery/pkg/runtime"
)

func (in *Project) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(Project)
	deepCopyJSON(in, out)
	return out
}

func (in *ProjectList) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(ProjectList)
	deepCopyJSON(in, out)
	return out
}

func (in *Repository) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(Repository)
	deepCopyJSON(in, out)
	return out
}

func (in *RepositoryList) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(RepositoryList)
	deepCopyJSON(in, out)
	return out
}

func (in *PipelineTemplate) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(PipelineTemplate)
	deepCopyJSON(in, out)
	return out
}

func (in *PipelineTemplateList) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(PipelineTemplateList)
	deepCopyJSON(in, out)
	return out
}

func (in *BuildRun) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(BuildRun)
	deepCopyJSON(in, out)
	return out
}

func (in *BuildRunList) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(BuildRunList)
	deepCopyJSON(in, out)
	return out
}

func (in *Environment) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(Environment)
	deepCopyJSON(in, out)
	return out
}

func (in *EnvironmentList) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(EnvironmentList)
	deepCopyJSON(in, out)
	return out
}

func (in *Release) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(Release)
	deepCopyJSON(in, out)
	return out
}

func (in *ReleaseList) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(ReleaseList)
	deepCopyJSON(in, out)
	return out
}

func deepCopyJSON(in, out any) {
	data, err := json.Marshal(in)
	if err != nil {
		panic(err)
	}
	if err := json.Unmarshal(data, out); err != nil {
		panic(err)
	}
}
