//go:build !ignore_autogenerated

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

func (in *Project) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(Project)
	*out = *in
	out.ObjectMeta = *in.ObjectMeta.DeepCopy()
	out.Status.Conditions = append([]metav1.Condition(nil), in.Status.Conditions...)
	return out
}

func (in *ProjectList) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(ProjectList)
	*out = *in
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		out.Items = make([]Project, len(in.Items))
		for i := range in.Items {
			out.Items[i] = *in.Items[i].DeepCopyObject().(*Project)
		}
	}
	return out
}

func (in *Repository) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(Repository)
	*out = *in
	out.ObjectMeta = *in.ObjectMeta.DeepCopy()
	out.Status.Conditions = append([]metav1.Condition(nil), in.Status.Conditions...)
	return out
}

func (in *RepositoryList) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(RepositoryList)
	*out = *in
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		out.Items = make([]Repository, len(in.Items))
		for i := range in.Items {
			out.Items[i] = *in.Items[i].DeepCopyObject().(*Repository)
		}
	}
	return out
}

func (in *PipelineTemplate) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(PipelineTemplate)
	*out = *in
	out.ObjectMeta = *in.ObjectMeta.DeepCopy()
	out.Spec.Steps = append([]string(nil), in.Spec.Steps...)
	out.Status.Conditions = append([]metav1.Condition(nil), in.Status.Conditions...)
	return out
}

func (in *PipelineTemplateList) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(PipelineTemplateList)
	*out = *in
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		out.Items = make([]PipelineTemplate, len(in.Items))
		for i := range in.Items {
			out.Items[i] = *in.Items[i].DeepCopyObject().(*PipelineTemplate)
		}
	}
	return out
}

func (in *BuildRun) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(BuildRun)
	*out = *in
	out.ObjectMeta = *in.ObjectMeta.DeepCopy()
	out.Status.Conditions = append([]metav1.Condition(nil), in.Status.Conditions...)
	return out
}

func (in *BuildRunList) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(BuildRunList)
	*out = *in
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		out.Items = make([]BuildRun, len(in.Items))
		for i := range in.Items {
			out.Items[i] = *in.Items[i].DeepCopyObject().(*BuildRun)
		}
	}
	return out
}

func (in *Environment) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(Environment)
	*out = *in
	out.ObjectMeta = *in.ObjectMeta.DeepCopy()
	out.Status.Conditions = append([]metav1.Condition(nil), in.Status.Conditions...)
	return out
}

func (in *EnvironmentList) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(EnvironmentList)
	*out = *in
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		out.Items = make([]Environment, len(in.Items))
		for i := range in.Items {
			out.Items[i] = *in.Items[i].DeepCopyObject().(*Environment)
		}
	}
	return out
}

func (in *Release) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(Release)
	*out = *in
	out.ObjectMeta = *in.ObjectMeta.DeepCopy()
	out.Status.Conditions = append([]metav1.Condition(nil), in.Status.Conditions...)
	return out
}

func (in *ReleaseList) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(ReleaseList)
	*out = *in
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		out.Items = make([]Release, len(in.Items))
		for i := range in.Items {
			out.Items[i] = *in.Items[i].DeepCopyObject().(*Release)
		}
	}
	return out
}
