apiVersion: cicd.cloudivision.io/v1alpha1
kind: BuildRun
metadata:
  generateName: cloudivision-go-
  namespace: cloudivision-dogfood
spec:
  projectRef: cloudivision
  repositoryRef: cloudivision
  pipelineTemplateRef: cloudivision-go
  revision: main
  branch: main
  triggeredBy:
    type: manual
    actor: dogfood
  image:
    repository: localhost:5001/cloudivision/controller
    tag: dogfood
  executor: job
  gitOps:
    enabled: false
